package com.vsm.platform.domain.enums;

public enum VSMNodeType {
    SUPPLIER, CUSTOMER, PROCESS, DATA_BOX,
    INVENTORY, SUPERMARKET, KAIZEN_BURST,
    ELECTRONIC_FLOW, MANUAL_FLOW, PUSH_ARROW,
    PULL_ARROW, FIFO_LANE, TRUCK_SHIPMENT
}